Prevent a build error in @lit-labs/react and @lit-labs/task.
Having this constant at the top level causes `extendedWindow` to be emitted in
'polyfill-support.d.ts', but without a reference to the `WindowWithLitExtras`
type. This causes @lit-labs/task and @lit-labs/react to fail to build with this
error:

```
> @lit-labs/task@1.0.0-rc.2 build:ts
> tsc --build && treemirror development . '**/*.d.ts{,.map}'

../../lit-html/polyfill-support.d.ts(67,31): error TS2304: Cannot find name 'WindowWithLitExtras'.
```