Cast `window` to a new type (instead of extending it) to prevent collisions. (#1904)
* lit-html: Stop extending the global `Window` type for polyfills and shared globals.

* Prevent a build error in @lit-labs/react and @lit-labs/task.

Having this constant at the top level causes `extendedWindow` to be emitted in
'polyfill-support.d.ts', but without a reference to the `WindowWithLitExtras`
type. This causes @lit-labs/task and @lit-labs/react to fail to build with this
error:

```
> @lit-labs/task@1.0.0-rc.2 build:ts
> tsc --build && treemirror development . '**/*.d.ts{,.map}'

../../lit-html/polyfill-support.d.ts(67,31): error TS2304: Cannot find name 'WindowWithLitExtras'.
```

* reactive-element: Stop extending the global `Window` type for polyfills and shared globals.

* lit-element: Stop extending the global `Window` type for polyfills and shared globals.

* Remove `ShadowRoot` property from `WindowWithLitExtras` interfaces.

* `WindowWithLitExtras` -> `LitExtraGlobals` - this interface does not extend `Window`.

* Revert a non-replacement change.

* `extendedWindow` -> `extraGlobals`

* lit-html: Make `LitExtraGlobals` extend `Window` to avoid casting through `unknown`.

* reactive-element: Make `LitExtraGlobals` extend `Window` to avoid casting through `unknown`.

* lit-element: Make `LitExtraGlobals` extend `Window` to avoid casting through `unknown`.

* Add new `LitExtendedWindow` type.

* Swap names of `LitExtraGlobals` and `LitExtendedWindow`.